// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logic_server.proto

#ifndef PROTOBUF_logic_5fserver_2eproto__INCLUDED
#define PROTOBUF_logic_5fserver_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace logic_server {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_logic_5fserver_2eproto();
void protobuf_InitDefaults_logic_5fserver_2eproto();
void protobuf_AssignDesc_logic_5fserver_2eproto();
void protobuf_ShutdownFile_logic_5fserver_2eproto();

class packet_disconnect_room_ntf;
class packet_echo_ntf;
class packet_enter_ans;
class packet_enter_req;
class packet_game_state_ntf;
class packet_process_check_card_ntf;
class packet_process_turn_ans;
class packet_process_turn_ntf;
class packet_process_turn_req;

enum message_type {
  ENTER_REQ = 0,
  ENTER_ANS = 1,
  GAME_STATE_NTF = 2,
  PROCESS_TURN_REQ = 3,
  PROCESS_TURN_ANS = 4,
  PROCESS_TURN_NTF = 5,
  PROCESS_CHECK_CARD_NTF = 6,
  DISCONNECT_ROOM = 7,
  ECHO_NTF = 8
};
bool message_type_IsValid(int value);
const message_type message_type_MIN = ENTER_REQ;
const message_type message_type_MAX = ECHO_NTF;
const int message_type_ARRAYSIZE = message_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* message_type_descriptor();
inline const ::std::string& message_type_Name(message_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    message_type_descriptor(), value);
}
inline bool message_type_Parse(
    const ::std::string& name, message_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<message_type>(
    message_type_descriptor(), name, value);
}
// ===================================================================

class packet_enter_req : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_enter_req) */ {
 public:
  packet_enter_req();
  virtual ~packet_enter_req();

  packet_enter_req(const packet_enter_req& from);

  inline packet_enter_req& operator=(const packet_enter_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_enter_req& default_instance();

  static const packet_enter_req* internal_default_instance();

  void Swap(packet_enter_req* other);

  // implements Message ----------------------------------------------

  inline packet_enter_req* New() const { return New(NULL); }

  packet_enter_req* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_enter_req& from);
  void MergeFrom(const packet_enter_req& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_enter_req* other);
  void UnsafeMergeFrom(const packet_enter_req& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string player_key = 1;
  bool has_player_key() const;
  void clear_player_key();
  static const int kPlayerKeyFieldNumber = 1;
  const ::std::string& player_key() const;
  void set_player_key(const ::std::string& value);
  void set_player_key(const char* value);
  void set_player_key(const char* value, size_t size);
  ::std::string* mutable_player_key();
  ::std::string* release_player_key();
  void set_allocated_player_key(::std::string* player_key);

  // required string room_key = 2;
  bool has_room_key() const;
  void clear_room_key();
  static const int kRoomKeyFieldNumber = 2;
  const ::std::string& room_key() const;
  void set_room_key(const ::std::string& value);
  void set_room_key(const char* value);
  void set_room_key(const char* value, size_t size);
  ::std::string* mutable_room_key();
  ::std::string* release_room_key();
  void set_allocated_room_key(::std::string* room_key);

  // @@protoc_insertion_point(class_scope:logic_server.packet_enter_req)
 private:
  inline void set_has_player_key();
  inline void clear_has_player_key();
  inline void set_has_room_key();
  inline void clear_has_room_key();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr player_key_;
  ::google::protobuf::internal::ArenaStringPtr room_key_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_enter_req> packet_enter_req_default_instance_;

// -------------------------------------------------------------------

class packet_enter_ans : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_enter_ans) */ {
 public:
  packet_enter_ans();
  virtual ~packet_enter_ans();

  packet_enter_ans(const packet_enter_ans& from);

  inline packet_enter_ans& operator=(const packet_enter_ans& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_enter_ans& default_instance();

  static const packet_enter_ans* internal_default_instance();

  void Swap(packet_enter_ans* other);

  // implements Message ----------------------------------------------

  inline packet_enter_ans* New() const { return New(NULL); }

  packet_enter_ans* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_enter_ans& from);
  void MergeFrom(const packet_enter_ans& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_enter_ans* other);
  void UnsafeMergeFrom(const packet_enter_ans& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:logic_server.packet_enter_ans)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_enter_ans> packet_enter_ans_default_instance_;

// -------------------------------------------------------------------

class packet_game_state_ntf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_game_state_ntf) */ {
 public:
  packet_game_state_ntf();
  virtual ~packet_game_state_ntf();

  packet_game_state_ntf(const packet_game_state_ntf& from);

  inline packet_game_state_ntf& operator=(const packet_game_state_ntf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_game_state_ntf& default_instance();

  static const packet_game_state_ntf* internal_default_instance();

  void Swap(packet_game_state_ntf* other);

  // implements Message ----------------------------------------------

  inline packet_game_state_ntf* New() const { return New(NULL); }

  packet_game_state_ntf* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_game_state_ntf& from);
  void MergeFrom(const packet_game_state_ntf& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_game_state_ntf* other);
  void UnsafeMergeFrom(const packet_game_state_ntf& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  bool has_state() const;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // required string win_player_key = 2;
  bool has_win_player_key() const;
  void clear_win_player_key();
  static const int kWinPlayerKeyFieldNumber = 2;
  const ::std::string& win_player_key() const;
  void set_win_player_key(const ::std::string& value);
  void set_win_player_key(const char* value);
  void set_win_player_key(const char* value, size_t size);
  ::std::string* mutable_win_player_key();
  ::std::string* release_win_player_key();
  void set_allocated_win_player_key(::std::string* win_player_key);

  // @@protoc_insertion_point(class_scope:logic_server.packet_game_state_ntf)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_win_player_key();
  inline void clear_has_win_player_key();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr win_player_key_;
  ::google::protobuf::int32 state_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_game_state_ntf> packet_game_state_ntf_default_instance_;

// -------------------------------------------------------------------

class packet_process_turn_req : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_process_turn_req) */ {
 public:
  packet_process_turn_req();
  virtual ~packet_process_turn_req();

  packet_process_turn_req(const packet_process_turn_req& from);

  inline packet_process_turn_req& operator=(const packet_process_turn_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_process_turn_req& default_instance();

  static const packet_process_turn_req* internal_default_instance();

  void Swap(packet_process_turn_req* other);

  // implements Message ----------------------------------------------

  inline packet_process_turn_req* New() const { return New(NULL); }

  packet_process_turn_req* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_process_turn_req& from);
  void MergeFrom(const packet_process_turn_req& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_process_turn_req* other);
  void UnsafeMergeFrom(const packet_process_turn_req& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 my_money = 1;
  bool has_my_money() const;
  void clear_my_money();
  static const int kMyMoneyFieldNumber = 1;
  ::google::protobuf::int32 my_money() const;
  void set_my_money(::google::protobuf::int32 value);

  // required int32 opponent_money = 2;
  bool has_opponent_money() const;
  void clear_opponent_money();
  static const int kOpponentMoneyFieldNumber = 2;
  ::google::protobuf::int32 opponent_money() const;
  void set_opponent_money(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:logic_server.packet_process_turn_req)
 private:
  inline void set_has_my_money();
  inline void clear_has_my_money();
  inline void set_has_opponent_money();
  inline void clear_has_opponent_money();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 my_money_;
  ::google::protobuf::int32 opponent_money_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_process_turn_req> packet_process_turn_req_default_instance_;

// -------------------------------------------------------------------

class packet_process_turn_ans : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_process_turn_ans) */ {
 public:
  packet_process_turn_ans();
  virtual ~packet_process_turn_ans();

  packet_process_turn_ans(const packet_process_turn_ans& from);

  inline packet_process_turn_ans& operator=(const packet_process_turn_ans& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_process_turn_ans& default_instance();

  static const packet_process_turn_ans* internal_default_instance();

  void Swap(packet_process_turn_ans* other);

  // implements Message ----------------------------------------------

  inline packet_process_turn_ans* New() const { return New(NULL); }

  packet_process_turn_ans* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_process_turn_ans& from);
  void MergeFrom(const packet_process_turn_ans& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_process_turn_ans* other);
  void UnsafeMergeFrom(const packet_process_turn_ans& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 money = 1;
  bool has_money() const;
  void clear_money();
  static const int kMoneyFieldNumber = 1;
  ::google::protobuf::int32 money() const;
  void set_money(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:logic_server.packet_process_turn_ans)
 private:
  inline void set_has_money();
  inline void clear_has_money();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 money_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_process_turn_ans> packet_process_turn_ans_default_instance_;

// -------------------------------------------------------------------

class packet_process_turn_ntf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_process_turn_ntf) */ {
 public:
  packet_process_turn_ntf();
  virtual ~packet_process_turn_ntf();

  packet_process_turn_ntf(const packet_process_turn_ntf& from);

  inline packet_process_turn_ntf& operator=(const packet_process_turn_ntf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_process_turn_ntf& default_instance();

  static const packet_process_turn_ntf* internal_default_instance();

  void Swap(packet_process_turn_ntf* other);

  // implements Message ----------------------------------------------

  inline packet_process_turn_ntf* New() const { return New(NULL); }

  packet_process_turn_ntf* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_process_turn_ntf& from);
  void MergeFrom(const packet_process_turn_ntf& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_process_turn_ntf* other);
  void UnsafeMergeFrom(const packet_process_turn_ntf& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 public_card_number_1 = 1;
  bool has_public_card_number_1() const;
  void clear_public_card_number_1();
  static const int kPublicCardNumber1FieldNumber = 1;
  ::google::protobuf::int32 public_card_number_1() const;
  void set_public_card_number_1(::google::protobuf::int32 value);

  // required int32 public_card_number_2 = 2;
  bool has_public_card_number_2() const;
  void clear_public_card_number_2();
  static const int kPublicCardNumber2FieldNumber = 2;
  ::google::protobuf::int32 public_card_number_2() const;
  void set_public_card_number_2(::google::protobuf::int32 value);

  // required int32 opponent_card_number = 3;
  bool has_opponent_card_number() const;
  void clear_opponent_card_number();
  static const int kOpponentCardNumberFieldNumber = 3;
  ::google::protobuf::int32 opponent_card_number() const;
  void set_opponent_card_number(::google::protobuf::int32 value);

  // required int32 remain_money = 4;
  bool has_remain_money() const;
  void clear_remain_money();
  static const int kRemainMoneyFieldNumber = 4;
  ::google::protobuf::int32 remain_money() const;
  void set_remain_money(::google::protobuf::int32 value);

  // required int32 my_money = 5;
  bool has_my_money() const;
  void clear_my_money();
  static const int kMyMoneyFieldNumber = 5;
  ::google::protobuf::int32 my_money() const;
  void set_my_money(::google::protobuf::int32 value);

  // required int32 opponent_money = 6;
  bool has_opponent_money() const;
  void clear_opponent_money();
  static const int kOpponentMoneyFieldNumber = 6;
  ::google::protobuf::int32 opponent_money() const;
  void set_opponent_money(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:logic_server.packet_process_turn_ntf)
 private:
  inline void set_has_public_card_number_1();
  inline void clear_has_public_card_number_1();
  inline void set_has_public_card_number_2();
  inline void clear_has_public_card_number_2();
  inline void set_has_opponent_card_number();
  inline void clear_has_opponent_card_number();
  inline void set_has_remain_money();
  inline void clear_has_remain_money();
  inline void set_has_my_money();
  inline void clear_has_my_money();
  inline void set_has_opponent_money();
  inline void clear_has_opponent_money();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 public_card_number_1_;
  ::google::protobuf::int32 public_card_number_2_;
  ::google::protobuf::int32 opponent_card_number_;
  ::google::protobuf::int32 remain_money_;
  ::google::protobuf::int32 my_money_;
  ::google::protobuf::int32 opponent_money_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_process_turn_ntf> packet_process_turn_ntf_default_instance_;

// -------------------------------------------------------------------

class packet_process_check_card_ntf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_process_check_card_ntf) */ {
 public:
  packet_process_check_card_ntf();
  virtual ~packet_process_check_card_ntf();

  packet_process_check_card_ntf(const packet_process_check_card_ntf& from);

  inline packet_process_check_card_ntf& operator=(const packet_process_check_card_ntf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_process_check_card_ntf& default_instance();

  static const packet_process_check_card_ntf* internal_default_instance();

  void Swap(packet_process_check_card_ntf* other);

  // implements Message ----------------------------------------------

  inline packet_process_check_card_ntf* New() const { return New(NULL); }

  packet_process_check_card_ntf* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_process_check_card_ntf& from);
  void MergeFrom(const packet_process_check_card_ntf& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_process_check_card_ntf* other);
  void UnsafeMergeFrom(const packet_process_check_card_ntf& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:logic_server.packet_process_check_card_ntf)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_process_check_card_ntf> packet_process_check_card_ntf_default_instance_;

// -------------------------------------------------------------------

class packet_disconnect_room_ntf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_disconnect_room_ntf) */ {
 public:
  packet_disconnect_room_ntf();
  virtual ~packet_disconnect_room_ntf();

  packet_disconnect_room_ntf(const packet_disconnect_room_ntf& from);

  inline packet_disconnect_room_ntf& operator=(const packet_disconnect_room_ntf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_disconnect_room_ntf& default_instance();

  static const packet_disconnect_room_ntf* internal_default_instance();

  void Swap(packet_disconnect_room_ntf* other);

  // implements Message ----------------------------------------------

  inline packet_disconnect_room_ntf* New() const { return New(NULL); }

  packet_disconnect_room_ntf* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_disconnect_room_ntf& from);
  void MergeFrom(const packet_disconnect_room_ntf& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_disconnect_room_ntf* other);
  void UnsafeMergeFrom(const packet_disconnect_room_ntf& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string room_key = 1;
  bool has_room_key() const;
  void clear_room_key();
  static const int kRoomKeyFieldNumber = 1;
  const ::std::string& room_key() const;
  void set_room_key(const ::std::string& value);
  void set_room_key(const char* value);
  void set_room_key(const char* value, size_t size);
  ::std::string* mutable_room_key();
  ::std::string* release_room_key();
  void set_allocated_room_key(::std::string* room_key);

  // @@protoc_insertion_point(class_scope:logic_server.packet_disconnect_room_ntf)
 private:
  inline void set_has_room_key();
  inline void clear_has_room_key();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr room_key_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_disconnect_room_ntf> packet_disconnect_room_ntf_default_instance_;

// -------------------------------------------------------------------

class packet_echo_ntf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_echo_ntf) */ {
 public:
  packet_echo_ntf();
  virtual ~packet_echo_ntf();

  packet_echo_ntf(const packet_echo_ntf& from);

  inline packet_echo_ntf& operator=(const packet_echo_ntf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packet_echo_ntf& default_instance();

  static const packet_echo_ntf* internal_default_instance();

  void Swap(packet_echo_ntf* other);

  // implements Message ----------------------------------------------

  inline packet_echo_ntf* New() const { return New(NULL); }

  packet_echo_ntf* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packet_echo_ntf& from);
  void MergeFrom(const packet_echo_ntf& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(packet_echo_ntf* other);
  void UnsafeMergeFrom(const packet_echo_ntf& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string str = 1;
  bool has_str() const;
  void clear_str();
  static const int kStrFieldNumber = 1;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // @@protoc_insertion_point(class_scope:logic_server.packet_echo_ntf)
 private:
  inline void set_has_str();
  inline void clear_has_str();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
  friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
  friend void protobuf_AssignDesc_logic_5fserver_2eproto();
  friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<packet_echo_ntf> packet_echo_ntf_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// packet_enter_req

// required string player_key = 1;
inline bool packet_enter_req::has_player_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_enter_req::set_has_player_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_enter_req::clear_has_player_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_enter_req::clear_player_key() {
  player_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_player_key();
}
inline const ::std::string& packet_enter_req::player_key() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_enter_req.player_key)
  return player_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_enter_req::set_player_key(const ::std::string& value) {
  set_has_player_key();
  player_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:logic_server.packet_enter_req.player_key)
}
inline void packet_enter_req::set_player_key(const char* value) {
  set_has_player_key();
  player_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:logic_server.packet_enter_req.player_key)
}
inline void packet_enter_req::set_player_key(const char* value, size_t size) {
  set_has_player_key();
  player_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:logic_server.packet_enter_req.player_key)
}
inline ::std::string* packet_enter_req::mutable_player_key() {
  set_has_player_key();
  // @@protoc_insertion_point(field_mutable:logic_server.packet_enter_req.player_key)
  return player_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* packet_enter_req::release_player_key() {
  // @@protoc_insertion_point(field_release:logic_server.packet_enter_req.player_key)
  clear_has_player_key();
  return player_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_enter_req::set_allocated_player_key(::std::string* player_key) {
  if (player_key != NULL) {
    set_has_player_key();
  } else {
    clear_has_player_key();
  }
  player_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), player_key);
  // @@protoc_insertion_point(field_set_allocated:logic_server.packet_enter_req.player_key)
}

// required string room_key = 2;
inline bool packet_enter_req::has_room_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void packet_enter_req::set_has_room_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void packet_enter_req::clear_has_room_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void packet_enter_req::clear_room_key() {
  room_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_room_key();
}
inline const ::std::string& packet_enter_req::room_key() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_enter_req.room_key)
  return room_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_enter_req::set_room_key(const ::std::string& value) {
  set_has_room_key();
  room_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:logic_server.packet_enter_req.room_key)
}
inline void packet_enter_req::set_room_key(const char* value) {
  set_has_room_key();
  room_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:logic_server.packet_enter_req.room_key)
}
inline void packet_enter_req::set_room_key(const char* value, size_t size) {
  set_has_room_key();
  room_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:logic_server.packet_enter_req.room_key)
}
inline ::std::string* packet_enter_req::mutable_room_key() {
  set_has_room_key();
  // @@protoc_insertion_point(field_mutable:logic_server.packet_enter_req.room_key)
  return room_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* packet_enter_req::release_room_key() {
  // @@protoc_insertion_point(field_release:logic_server.packet_enter_req.room_key)
  clear_has_room_key();
  return room_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_enter_req::set_allocated_room_key(::std::string* room_key) {
  if (room_key != NULL) {
    set_has_room_key();
  } else {
    clear_has_room_key();
  }
  room_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), room_key);
  // @@protoc_insertion_point(field_set_allocated:logic_server.packet_enter_req.room_key)
}

inline const packet_enter_req* packet_enter_req::internal_default_instance() {
  return &packet_enter_req_default_instance_.get();
}
// -------------------------------------------------------------------

// packet_enter_ans

// required int32 result = 1;
inline bool packet_enter_ans::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_enter_ans::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_enter_ans::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_enter_ans::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 packet_enter_ans::result() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_enter_ans.result)
  return result_;
}
inline void packet_enter_ans::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_enter_ans.result)
}

inline const packet_enter_ans* packet_enter_ans::internal_default_instance() {
  return &packet_enter_ans_default_instance_.get();
}
// -------------------------------------------------------------------

// packet_game_state_ntf

// required int32 state = 1;
inline bool packet_game_state_ntf::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_game_state_ntf::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_game_state_ntf::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_game_state_ntf::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 packet_game_state_ntf::state() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_game_state_ntf.state)
  return state_;
}
inline void packet_game_state_ntf::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_game_state_ntf.state)
}

// required string win_player_key = 2;
inline bool packet_game_state_ntf::has_win_player_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void packet_game_state_ntf::set_has_win_player_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void packet_game_state_ntf::clear_has_win_player_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void packet_game_state_ntf::clear_win_player_key() {
  win_player_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_win_player_key();
}
inline const ::std::string& packet_game_state_ntf::win_player_key() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_game_state_ntf.win_player_key)
  return win_player_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_game_state_ntf::set_win_player_key(const ::std::string& value) {
  set_has_win_player_key();
  win_player_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:logic_server.packet_game_state_ntf.win_player_key)
}
inline void packet_game_state_ntf::set_win_player_key(const char* value) {
  set_has_win_player_key();
  win_player_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:logic_server.packet_game_state_ntf.win_player_key)
}
inline void packet_game_state_ntf::set_win_player_key(const char* value, size_t size) {
  set_has_win_player_key();
  win_player_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:logic_server.packet_game_state_ntf.win_player_key)
}
inline ::std::string* packet_game_state_ntf::mutable_win_player_key() {
  set_has_win_player_key();
  // @@protoc_insertion_point(field_mutable:logic_server.packet_game_state_ntf.win_player_key)
  return win_player_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* packet_game_state_ntf::release_win_player_key() {
  // @@protoc_insertion_point(field_release:logic_server.packet_game_state_ntf.win_player_key)
  clear_has_win_player_key();
  return win_player_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_game_state_ntf::set_allocated_win_player_key(::std::string* win_player_key) {
  if (win_player_key != NULL) {
    set_has_win_player_key();
  } else {
    clear_has_win_player_key();
  }
  win_player_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), win_player_key);
  // @@protoc_insertion_point(field_set_allocated:logic_server.packet_game_state_ntf.win_player_key)
}

inline const packet_game_state_ntf* packet_game_state_ntf::internal_default_instance() {
  return &packet_game_state_ntf_default_instance_.get();
}
// -------------------------------------------------------------------

// packet_process_turn_req

// required int32 my_money = 1;
inline bool packet_process_turn_req::has_my_money() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_process_turn_req::set_has_my_money() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_process_turn_req::clear_has_my_money() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_process_turn_req::clear_my_money() {
  my_money_ = 0;
  clear_has_my_money();
}
inline ::google::protobuf::int32 packet_process_turn_req::my_money() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_req.my_money)
  return my_money_;
}
inline void packet_process_turn_req::set_my_money(::google::protobuf::int32 value) {
  set_has_my_money();
  my_money_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_req.my_money)
}

// required int32 opponent_money = 2;
inline bool packet_process_turn_req::has_opponent_money() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void packet_process_turn_req::set_has_opponent_money() {
  _has_bits_[0] |= 0x00000002u;
}
inline void packet_process_turn_req::clear_has_opponent_money() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void packet_process_turn_req::clear_opponent_money() {
  opponent_money_ = 0;
  clear_has_opponent_money();
}
inline ::google::protobuf::int32 packet_process_turn_req::opponent_money() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_req.opponent_money)
  return opponent_money_;
}
inline void packet_process_turn_req::set_opponent_money(::google::protobuf::int32 value) {
  set_has_opponent_money();
  opponent_money_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_req.opponent_money)
}

inline const packet_process_turn_req* packet_process_turn_req::internal_default_instance() {
  return &packet_process_turn_req_default_instance_.get();
}
// -------------------------------------------------------------------

// packet_process_turn_ans

// required int32 money = 1;
inline bool packet_process_turn_ans::has_money() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_process_turn_ans::set_has_money() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_process_turn_ans::clear_has_money() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_process_turn_ans::clear_money() {
  money_ = 0;
  clear_has_money();
}
inline ::google::protobuf::int32 packet_process_turn_ans::money() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ans.money)
  return money_;
}
inline void packet_process_turn_ans::set_money(::google::protobuf::int32 value) {
  set_has_money();
  money_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ans.money)
}

inline const packet_process_turn_ans* packet_process_turn_ans::internal_default_instance() {
  return &packet_process_turn_ans_default_instance_.get();
}
// -------------------------------------------------------------------

// packet_process_turn_ntf

// required int32 public_card_number_1 = 1;
inline bool packet_process_turn_ntf::has_public_card_number_1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_process_turn_ntf::set_has_public_card_number_1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_process_turn_ntf::clear_has_public_card_number_1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_process_turn_ntf::clear_public_card_number_1() {
  public_card_number_1_ = 0;
  clear_has_public_card_number_1();
}
inline ::google::protobuf::int32 packet_process_turn_ntf::public_card_number_1() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ntf.public_card_number_1)
  return public_card_number_1_;
}
inline void packet_process_turn_ntf::set_public_card_number_1(::google::protobuf::int32 value) {
  set_has_public_card_number_1();
  public_card_number_1_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ntf.public_card_number_1)
}

// required int32 public_card_number_2 = 2;
inline bool packet_process_turn_ntf::has_public_card_number_2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void packet_process_turn_ntf::set_has_public_card_number_2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void packet_process_turn_ntf::clear_has_public_card_number_2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void packet_process_turn_ntf::clear_public_card_number_2() {
  public_card_number_2_ = 0;
  clear_has_public_card_number_2();
}
inline ::google::protobuf::int32 packet_process_turn_ntf::public_card_number_2() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ntf.public_card_number_2)
  return public_card_number_2_;
}
inline void packet_process_turn_ntf::set_public_card_number_2(::google::protobuf::int32 value) {
  set_has_public_card_number_2();
  public_card_number_2_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ntf.public_card_number_2)
}

// required int32 opponent_card_number = 3;
inline bool packet_process_turn_ntf::has_opponent_card_number() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void packet_process_turn_ntf::set_has_opponent_card_number() {
  _has_bits_[0] |= 0x00000004u;
}
inline void packet_process_turn_ntf::clear_has_opponent_card_number() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void packet_process_turn_ntf::clear_opponent_card_number() {
  opponent_card_number_ = 0;
  clear_has_opponent_card_number();
}
inline ::google::protobuf::int32 packet_process_turn_ntf::opponent_card_number() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ntf.opponent_card_number)
  return opponent_card_number_;
}
inline void packet_process_turn_ntf::set_opponent_card_number(::google::protobuf::int32 value) {
  set_has_opponent_card_number();
  opponent_card_number_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ntf.opponent_card_number)
}

// required int32 remain_money = 4;
inline bool packet_process_turn_ntf::has_remain_money() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void packet_process_turn_ntf::set_has_remain_money() {
  _has_bits_[0] |= 0x00000008u;
}
inline void packet_process_turn_ntf::clear_has_remain_money() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void packet_process_turn_ntf::clear_remain_money() {
  remain_money_ = 0;
  clear_has_remain_money();
}
inline ::google::protobuf::int32 packet_process_turn_ntf::remain_money() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ntf.remain_money)
  return remain_money_;
}
inline void packet_process_turn_ntf::set_remain_money(::google::protobuf::int32 value) {
  set_has_remain_money();
  remain_money_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ntf.remain_money)
}

// required int32 my_money = 5;
inline bool packet_process_turn_ntf::has_my_money() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void packet_process_turn_ntf::set_has_my_money() {
  _has_bits_[0] |= 0x00000010u;
}
inline void packet_process_turn_ntf::clear_has_my_money() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void packet_process_turn_ntf::clear_my_money() {
  my_money_ = 0;
  clear_has_my_money();
}
inline ::google::protobuf::int32 packet_process_turn_ntf::my_money() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ntf.my_money)
  return my_money_;
}
inline void packet_process_turn_ntf::set_my_money(::google::protobuf::int32 value) {
  set_has_my_money();
  my_money_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ntf.my_money)
}

// required int32 opponent_money = 6;
inline bool packet_process_turn_ntf::has_opponent_money() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void packet_process_turn_ntf::set_has_opponent_money() {
  _has_bits_[0] |= 0x00000020u;
}
inline void packet_process_turn_ntf::clear_has_opponent_money() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void packet_process_turn_ntf::clear_opponent_money() {
  opponent_money_ = 0;
  clear_has_opponent_money();
}
inline ::google::protobuf::int32 packet_process_turn_ntf::opponent_money() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ntf.opponent_money)
  return opponent_money_;
}
inline void packet_process_turn_ntf::set_opponent_money(::google::protobuf::int32 value) {
  set_has_opponent_money();
  opponent_money_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ntf.opponent_money)
}

inline const packet_process_turn_ntf* packet_process_turn_ntf::internal_default_instance() {
  return &packet_process_turn_ntf_default_instance_.get();
}
// -------------------------------------------------------------------

// packet_process_check_card_ntf

// required int32 result = 1;
inline bool packet_process_check_card_ntf::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_process_check_card_ntf::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_process_check_card_ntf::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_process_check_card_ntf::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 packet_process_check_card_ntf::result() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_process_check_card_ntf.result)
  return result_;
}
inline void packet_process_check_card_ntf::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:logic_server.packet_process_check_card_ntf.result)
}

inline const packet_process_check_card_ntf* packet_process_check_card_ntf::internal_default_instance() {
  return &packet_process_check_card_ntf_default_instance_.get();
}
// -------------------------------------------------------------------

// packet_disconnect_room_ntf

// required string room_key = 1;
inline bool packet_disconnect_room_ntf::has_room_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_disconnect_room_ntf::set_has_room_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_disconnect_room_ntf::clear_has_room_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_disconnect_room_ntf::clear_room_key() {
  room_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_room_key();
}
inline const ::std::string& packet_disconnect_room_ntf::room_key() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_disconnect_room_ntf.room_key)
  return room_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_disconnect_room_ntf::set_room_key(const ::std::string& value) {
  set_has_room_key();
  room_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:logic_server.packet_disconnect_room_ntf.room_key)
}
inline void packet_disconnect_room_ntf::set_room_key(const char* value) {
  set_has_room_key();
  room_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:logic_server.packet_disconnect_room_ntf.room_key)
}
inline void packet_disconnect_room_ntf::set_room_key(const char* value, size_t size) {
  set_has_room_key();
  room_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:logic_server.packet_disconnect_room_ntf.room_key)
}
inline ::std::string* packet_disconnect_room_ntf::mutable_room_key() {
  set_has_room_key();
  // @@protoc_insertion_point(field_mutable:logic_server.packet_disconnect_room_ntf.room_key)
  return room_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* packet_disconnect_room_ntf::release_room_key() {
  // @@protoc_insertion_point(field_release:logic_server.packet_disconnect_room_ntf.room_key)
  clear_has_room_key();
  return room_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_disconnect_room_ntf::set_allocated_room_key(::std::string* room_key) {
  if (room_key != NULL) {
    set_has_room_key();
  } else {
    clear_has_room_key();
  }
  room_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), room_key);
  // @@protoc_insertion_point(field_set_allocated:logic_server.packet_disconnect_room_ntf.room_key)
}

inline const packet_disconnect_room_ntf* packet_disconnect_room_ntf::internal_default_instance() {
  return &packet_disconnect_room_ntf_default_instance_.get();
}
// -------------------------------------------------------------------

// packet_echo_ntf

// required string str = 1;
inline bool packet_echo_ntf::has_str() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packet_echo_ntf::set_has_str() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packet_echo_ntf::clear_has_str() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packet_echo_ntf::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_str();
}
inline const ::std::string& packet_echo_ntf::str() const {
  // @@protoc_insertion_point(field_get:logic_server.packet_echo_ntf.str)
  return str_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_echo_ntf::set_str(const ::std::string& value) {
  set_has_str();
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:logic_server.packet_echo_ntf.str)
}
inline void packet_echo_ntf::set_str(const char* value) {
  set_has_str();
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:logic_server.packet_echo_ntf.str)
}
inline void packet_echo_ntf::set_str(const char* value, size_t size) {
  set_has_str();
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:logic_server.packet_echo_ntf.str)
}
inline ::std::string* packet_echo_ntf::mutable_str() {
  set_has_str();
  // @@protoc_insertion_point(field_mutable:logic_server.packet_echo_ntf.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* packet_echo_ntf::release_str() {
  // @@protoc_insertion_point(field_release:logic_server.packet_echo_ntf.str)
  clear_has_str();
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void packet_echo_ntf::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    set_has_str();
  } else {
    clear_has_str();
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:logic_server.packet_echo_ntf.str)
}

inline const packet_echo_ntf* packet_echo_ntf::internal_default_instance() {
  return &packet_echo_ntf_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace logic_server

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::logic_server::message_type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::logic_server::message_type>() {
  return ::logic_server::message_type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_logic_5fserver_2eproto__INCLUDED
